name: custom_text_widget
description: Rich Text Formatting Support for custom fonts, colors, and styling.
version: 1.0.0
homepage: https://github.com/PradeepGIT27
repository: https://github.com/PradeepGIT27/Custom-Text-Widget
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
